# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state.proto',
  package='state',
  syntax='proto2',
  serialized_options=b'\n\022com.ulmefors.stateB\005StateZ\013state;state',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstate.proto\x12\x05state\"1\n\x0cStateMetrics\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x42(\n\x12\x63om.ulmefors.stateB\x05StateZ\x0bstate;state'
)




_STATEMETRICS = _descriptor.Descriptor(
  name='StateMetrics',
  full_name='state.StateMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='state.StateMetrics.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='state.StateMetrics.temperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['StateMetrics'] = _STATEMETRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateMetrics = _reflection.GeneratedProtocolMessageType('StateMetrics', (_message.Message,), {
  'DESCRIPTOR' : _STATEMETRICS,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:state.StateMetrics)
  })
_sym_db.RegisterMessage(StateMetrics)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
